---
pagetitle: ie:Intro

---

# Introduction the Integrated Ethics Curriculum

The Integrated Ethics Curriculum for the Computer and Data Sciences is an
on-going project with the goal of providing professor and student-friendly
ethics labs that can be integrated into computer and data science core courses. We
believe, as have others before us, that ethics have become an increasingly
important part of the undergraduate education of students in these disciplines.
Furthermore, we believe that ethics studies should be progressive, and included
in all four years of the student experience. 

## Curriculum Structure

### Year 1: Laying a foundation

While a particular lab can be used in isolation, our experience
shows that laying the groundwork with the first year curriculum prepares the
students to gain more from subsequent course-correlated labs. If you do choose
to use a lab in isolation, we recommend that you have the students complete the
[*A First Look at Ethics in Computer and Data Sciences*]() lab as homework prior 
to presenting the isolated lab.

The first year of the curriculum introduces a toolkit of frameworks for use in
evaluating approaches to ethical dilemmas. The use of these framework tools is
encouraged throughout the curriculum as a way of pushing students to reason
through the big picture and potential solutions rather than simply voicing an
impulsive opinion. The most useful framework for a given situation can then be
used to support and articulate a more thoughtful opinion.

Four frameworks are presented first in year one and then used and reinforced in the
subsequent years. The first three frameworks are frequently used in ethics
textbooks, but we see the use of analogies as complementary.
The **virtue ethics framework** encourages the student to answer the questions "What
approach would a virtuous person take?” and “Which virtues would this decision
uphold?"
The **utilitarian framework** asks the student to consider who this decision
would affect and to try to determine if the benefits of the outcome to some
outweigh the costs to others. In other words, does the chosen approach bring the
most "utility" or happiness to the most people?
The **deontological framework** informs a decision based on a set of rules such
as state laws or religious commandments or a company code of ethics.

Sometimes, before any of these frameworks can be used, it is helpful to just
understand the situation better. The computer and data science fields are new
enough and dynamic enough that there may be limited or no precedence for dealing
with a particular situation. This is where an **analogy** can be helpful. An analogy
is saying something is like something else for the purpose of clarification.
If a concept is better understood in an alogous situation than in dilemma in
question, the analogy might help in understanding the less-familiar predicament.

### Year 2 and 3: Applications

The labs in years two through four are more applied. They are designed to fit
with the content of a particular course. For example, an ethics lab to be
integrated into a Data Analysis course might deal with the potential for
unethical choices in data cleaning, while a lab to be integrated into a Software
Engineering course might deal with the addictive aspects of certain software
products.

## Recommendations for using the labs

We recommend that no faculty member be "forced" to present one of the labs. It
is important for the students to see the labs as a significant and integral part
of the course. A faculty member who presents the material under duress can
influence students negatively.

Recognize that you, as a professor, are presenting material that is
interdisciplinary in nature. While you are the content (computer, statistics,
data science) expert, you are not an expert in ethics. You will feel awkward at
times in presenting the ethics side of the lab. However, this makes you an
excellent role model for students who are also not ethics experts but who will
need to address ethical issues in their future occupations. Comfort will be
gained as you present a lab a second or third time and are able to adapt it to
your personal style

The ethics labs employ a variety of activities and feedback shows that students
find them to be quite engaging. It is often the case that students who rarely
speak up in class will be quite vocal with this material. Therefore, while each
lab could be completed in about 30 minutes, be prepared to be flexible regarding
time.

Each lab provides to the professor the following:
Ethics and content knowledge prerequisites
Learning objectives
A summary of the lab
A step-by-step guide for administering the lab
Student handouts if applicable
Assessment ideas

While the labs are designed to be somewhat “off-the-shelf”, the best results occur when the professor prepares in the following ways:
Read the entire module several times to familiarize yourself with the material
Print or post online any student handouts
Adapt the module for the size and personality of the course.
If a lab is used without any previous introduction to ethics, we recommend that you have the students complete the “A First Look at Ethics in Computer and Data Sciences” lab as homework prior to presenting the isolated lab.
