---
title: "Ethical Frameworks"
institute: "Integrated Ethics Labs"
date: "2022/05/26"
output:
   xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      ratio: 16:10
---


# Virtue Ethics

<!-- An ethical decision-making framework derived from the  -->
<!-- **moral values that a society has in common**.  -->

From the [Stanford Encyclopedia of Philosphy](https://plato.stanford.edu/entries/ethics-virtue/#Virt):

> A virtue is an excellent trait of character. It is a disposition, well
entrenched in its possessor—something that, as we say, goes all the way down,
unlike a habit such as being a tea-drinker—to notice, expect, value, feel,
desire, choose, act, and react in certain characteristic ways. 
**To possess a virtue is to be a certain sort of person** with a certain 
complex mindset.

Examples of virtues might
include compassion, courage, generosity, gratitude, honesty, humility,
inclusion, integrity, justice, mercy, open-mindedness, perseverance, respect,
and transparency, but there are many others. 
An activity might be considered
unethical it if conflicts with one or more of a person's or society’s virtues.

### Key Questions

* What sort of person would act this way?
* What sort of person do you want to be?

---

# Deontological Ethics 

In a deontological framework, determining whether something is right or wrong is
based on **adherence to certain moral principles** such as traffic laws, a
company’s code of ethics, or The Ten Commandments.

In a government context, this set of principles might be the US
Constitution or the UN Charter of Human Rights. The primary computing
organization (the ACM) has its own code of ethics as do many business,
scientific, and medical organizations. A well-known principal from the American
Medical Association is "Do no harm". Another deontological principle could be
"Give credit where it is due."

deontology = "science of duty"

### Key Question

* What rule(s) does this action uphold/violate?
* What are the moral rules/principles that must/should be followed?

---

# Utilitarianism (Consequentialism)

In consequentialist ethics, the ethics of a situation is decided by performing a
**cost-benefit analysis** based on the **consequences** of a proposed action.
A course of action is more ethical if it brings **more benefit to more people**
(or causes less harm).

For example, vaccinations are considered to be the ethical choice by most in our
society because they protect the general population (the majority stakeholder)
from spread of disease.

### Key Questions

* Who benefits from this action? How much?
* Who is harmed by this action? How much?
* What things do we consider to be benefits and harms?

---

# Analogy

Analogy is not so much a framework as a strategy. Sometimes investigating 
the ethics of an analogous situation helps shed light on the situation 
of interest.

### Key Question

* What other similar situation can help me understand how I should act?