---
title: "A First Look at Ethics in Computer and Data Sciences"
author: "TODO"
date: "2021-06-29"
output:
  blogdown::html_page:
    toc: true
    fig_width: 6
    dev: "svg"
---

A First Look at Ethics in Computer and Data Sciences

Module Summary

 

**Ethics background** required: None

**Subject matter** referred to in this module: computer and data science
tasks

**Placement** in overall ethics curriculum:

         Academic year: First year, first semester, probably
introductory programming course

         Recommended previous modules: Why Ethics?

         Recommended follow-up modules: Virtue Ethics* *

**Time required:**

         In class: 25 minutes

**Learning objectives:**

-   Students are introduced to the 3 ethical frameworks that are
    > considered in future modules

-   Students become familiar with virtue-terms

-   Students understand that virtues are characteristics that can be the
    > basis for wise decisions

-   Students have the opportunity to see that the relative importance of
    > virtues differs even within their own peer group

-   Students have opportunities to practice thoughtfully articulating
    > their convictions

**Module overview:**

[Ethical issue to be considered]{.ul}: This module does not address a
particular ethical issue, but rather introduces three ways of
determining the ethical thing, or "the right thing to do." More time is
spent considering how positive character traits, or virtues, can help us
to make wise decisions.

In a previous module, ethics was defined as "the study of what it means
to 'do the right thing.'". The question then, is how do we know what is
the right thing? This module introduces the 3 ethical frameworks used in
future modules. It begins to consider the virtue ethics framework at a
very high level.

[Exercise flow:]{.ul}

-   Students are reminded of what "ethics" is

-   Students are introduced to the three ethical frameworks to be
    > applied in future modules

-   Activity: Students are asked to reflect on someone who they believe
    > is of high moral character

-   Reflection: Students hear about the heroes of others, and reflect on
    > how the relative importance of certain virtues might vary among
    > their peers.

**Preparation required:** Read the entire module. Print a copy of the
student handout for each student in the class or make it available
online.

 

Instructors Guide

[Introduction (5 minutes)]{.ul}

Read or summarize the following:

"Ethics is the study of what it means to 'do the right thing.'" Sara
Basse, *A Gift of Fire*

But how do we know what is "the right thing"?

There are 3 approaches to determining the "right thing" often found in
ethics textbooks.

One is the **deontological approach** or framework. This framework is
based on a set of rules such as company rules, government rules, or
religious rules such as the Ten Commandments. If the action in question
adheres to the rules, it is considered to be the right thing to do in
that context.

Another common approach uses the **utilitarian framework**. There are
many varieties of this approach, but the basic idea is that the right
thing to do is the thing that brings the most utility, or happiness, to
the most people. While the action may help some and hurt others, if the
benefits to some outweigh the costs to others, the action is "the right
thing."

The third framework, **virtue ethics**, takes a completely different
approach---it examines the background of our moral decisions and
actions. For example, it asks how a person who is generous will see a
situation and its moral demands differently than someone who is greedy.
The "right thing to do" is the thing that would be chosen by the
virtuous person.

Utilitarianism and deontology are helpful and interesting concepts, but
virtue ethics is often the easiest to grasp. Most of us have at least
one person that we admire for making wise choices. Today we'll begin
thinking about ethics by considering the virtues that that wise person
might have to enable their wise decisions.

[Activity (10 minutes)]{.ul}

Hand out (or point students to an online version of) the Moral Heroes
Activity

Allow students 7-10 minutes to contemplate and fill out this paper

[Reflection (10 minutes)]{.ul}

In this module, students are asked to openly discuss virtues. To
encourage authentic engagement with the material and each other, you may
need to state some guidelines on expectations of peer-to-peer
interaction. Here are two suggestions from "Guidelines For Classroom
Interactions", the Center for Research on Learning & Teaching,
University of Michigan,
[[http://crlt.umich.edu/examples-discussion-guidelines]{.ul}](http://crlt.umich.edu/examples-discussion-guidelines).

1.  **Understand that your words have effects on others.** Speak with
    care. If you learn that something you have said was experienced as
    disrespectful or marginalizing, listen carefully and try to
    understand that perspective. Learn how you can do better in the
    future.

2.  **Understand that others will come to these discussions with
    different experiences from yours.** Be careful about assumptions and
    generalization you make based only on your experience. Be open to
    hearing and learning from other perspectives.

Ask several students to share about their moral hero -- with or without
a name attached. As each student shares, do the following:

-   Have student describe their hero, sharing a specific story if they
    > have one.

-   Have student list the virtues that they would attribute to this
    > person

-   Have the student rank the 2 that they think are most important

-   Ask class if there was one in the list that was not mentioned as a
    > top two that they would have chosen in their top 2 and why

Reflect on the fact that relative importance of virtues could vary
between people

[Assessment]{.ul} (to be included later on a quiz, paper, or exam to
determine if learning objectives were reached)

-   Ask students to define "virtue" and to list 5 virtues

-   Ask students to provide one method other than virtue ethics for
    > deciding "the right thing."

Moral Heroes Exercise

In her book, *Glittering Vices*, Rebecca DeYoung defines virtues as
"excellence of character, habits or dispositions of character that help
us live well as excellent human beings." Using courage as an example of
a virtue, she explains, "A courageous friend stands up for us when our
reputation is unfairly maligned, despite risk to his own personal or
professional reputation."

In addition to generosity and courage, here are some commonly-listed
virtues:

Adaptability

Attentiveness

Authenticity

Commitment

Compassion

Contentment

Cooperation

Excellence

Faithfulness

Gratitude

Honesty

Hospitality

Humility

Inclusive

Integrity

Justice

Kindness

Loyalty

Mercy

Moderation

Open-mindedness

Patience

Perseverance

Professionalism

Provide for others

Quality

Reliability

Respect

Self-discipline

Service

Sustainability

Tact

Who is the wisest, most virtuous, morally admirable person you know?
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

-   What virtues would you say characterize them?

Name at least 5-6 of them. (Use your own terms OR choose from the
virtue-term list above.)

\_\_\_\_\_\_\_\_\_\_\_ \_\_\_\_\_\_\_\_\_\_\_\_ \_\_\_\_\_\_\_\_\_\_\_\_
\_\_\_\_\_\_\_\_\_\_\_\_ \_\_\_\_\_\_\_\_\_\_\_\_
\_\_\_\_\_\_\_\_\_\_\_\_

-   Now try to rank those virtues in order of their importance. Does
    > your hero have a "signature" or "defining" virtue that captures
    > their overall character?

-   Can you tell a story that illustrates [why]{.ul} this person is
    > admirable or showcases what you mean by a particular
    > virtue-attribution?
